### ISSUE TITLE
Backend & Frontend Routes

### ISSUE THREAD

**Issue by paulobocanegra** [michaelyshih/soulcandy#3]
# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain superfluous routes
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by paulobocanegra** [comment]
Backend routes are snake_case (Rubyland). We just need to update our cartItems routes. Everything else looks great! 👍

**Comment by michaelyshih** [comment]
ok, done

**Comment by paulobocanegra** [comment]
I may not have been very specific:

cart_items
GET /api/cartItems - getting all items in the cart 
POST /api/cartItems - adding items into the cart
DELETE /api/cartItems/:id - removing items from cart
PATCH/PUT /api/cartItems/:id - edit the amount on a specific item

These are the routes I meant.

https://github.com/michaelyshih/soulcandy/wiki/backend-routes

**Comment by michaelyshih** [comment]
done

**Comment by michaelyshih** [comment]
i did add a seperate joins table into my schema though.
shouldn't that be part of my backend routes to store in the state too?

**Comment by paulobocanegra** [comment]
Excellent work! 💯
